# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "gocd-workshop-start"
  config.vm.box_url = "gocd-workshop-start.box"

  config.vm.network "forwarded_port", guest: 80, host: 8888, auto_correct: true
  config.vm.network "forwarded_port", guest: 8153, host: 8153, auto_correct: true

end
